version: "3.9"
services:
  netcat:
    build: 
      context: ./netcat
    ports:
      - 25566:25565
    stdin_open: true 
    tty: true
    depends_on: 
      - ngrok
    restart: always

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN
    command: 'tcp netcat:25565'
    ports:
      - 4040:4040