/* Generated by Yosys 0.28+4 (git sha1 7efc50367, clang 15.0.7 -fPIC -Os) */

(* top =  1  *)
(* src = "chal.v:3.1-3459.10" *)
module chip(io_12_31_1, io_18_31_0, io_21_0_1, io_19_0_1);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  (* src = "chal.v:3395.64-3395.80" *)
  wire _201_;
  (* src = "chal.v:3.20-3.30" *)
  input io_12_31_1;
  wire io_12_31_1;
  (* src = "chal.v:3.39-3.49" *)
  output io_18_31_0;
  reg io_18_31_0 = 1'h0;
  (* src = "chal.v:3.74-3.83" *)
  input io_19_0_1;
  wire io_19_0_1;
  (* src = "chal.v:3.57-3.66" *)
  input io_21_0_1;
  wire io_21_0_1;
  (* src = "chal.v:211.5-211.8" *)
  reg n10 = 1'h0;
  (* src = "chal.v:1674.6-1674.10" *)
  wire n101;
  (* src = "chal.v:1689.5-1689.9" *)
  reg n102 = 1'h0;
  (* src = "chal.v:1706.5-1706.9" *)
  reg n103 = 1'h0;
  (* src = "chal.v:1723.5-1723.9" *)
  reg n104 = 1'h0;
  (* src = "chal.v:1740.5-1740.9" *)
  reg n105 = 1'h0;
  (* src = "chal.v:1757.5-1757.9" *)
  reg n106 = 1'h0;
  (* src = "chal.v:1774.5-1774.9" *)
  reg n107 = 1'h0;
  (* src = "chal.v:225.5-225.8" *)
  reg n11 = 1'h0;
  (* src = "chal.v:1824.6-1824.10" *)
  wire n110;
  (* src = "chal.v:1842.5-1842.9" *)
  reg n111 = 1'h0;
  (* src = "chal.v:1859.5-1859.9" *)
  reg n112 = 1'h0;
  (* src = "chal.v:1876.5-1876.9" *)
  reg n113 = 1'h0;
  (* src = "chal.v:1893.5-1893.9" *)
  reg n114 = 1'h0;
  (* src = "chal.v:1910.5-1910.9" *)
  reg n115 = 1'h0;
  (* src = "chal.v:1927.5-1927.9" *)
  reg n116 = 1'h0;
  (* src = "chal.v:1944.5-1944.9" *)
  reg n117 = 1'h0;
  (* src = "chal.v:1966.5-1966.9" *)
  reg n119 = 1'h0;
  (* src = "chal.v:239.5-239.8" *)
  reg n12 = 1'h0;
  (* src = "chal.v:1982.5-1982.9" *)
  reg n120 = 1'h0;
  (* src = "chal.v:1999.5-1999.9" *)
  reg n121 = 1'h0;
  (* src = "chal.v:2016.5-2016.9" *)
  reg n122 = 1'h0;
  (* src = "chal.v:2033.5-2033.9" *)
  reg n123 = 1'h0;
  (* src = "chal.v:2050.5-2050.9" *)
  reg n124 = 1'h0;
  (* src = "chal.v:2067.5-2067.9" *)
  reg n125 = 1'h0;
  (* src = "chal.v:2084.5-2084.9" *)
  reg n126 = 1'h0;
  (* src = "chal.v:2101.5-2101.9" *)
  reg n127 = 1'h0;
  (* src = "chal.v:2123.5-2123.9" *)
  reg n129 = 1'h0;
  (* src = "chal.v:2140.5-2140.9" *)
  reg n130 = 1'h0;
  (* src = "chal.v:2157.5-2157.9" *)
  reg n131 = 1'h0;
  (* src = "chal.v:2174.5-2174.9" *)
  reg n132 = 1'h0;
  (* src = "chal.v:2191.5-2191.9" *)
  reg n133 = 1'h0;
  (* src = "chal.v:2208.5-2208.9" *)
  reg n134 = 1'h0;
  (* src = "chal.v:2225.5-2225.9" *)
  reg n135 = 1'h0;
  (* src = "chal.v:2256.5-2256.9" *)
  reg n136 = 1'h0;
  (* src = "chal.v:2293.5-2293.9" *)
  reg n138 = 1'h0;
  (* src = "chal.v:266.5-266.8" *)
  reg n14 = 1'h0;
  (* src = "chal.v:293.5-293.8" *)
  reg n16 = 1'h0;
  (* src = "chal.v:320.5-320.8" *)
  reg n18 = 1'h0;
  (* src = "chal.v:2596.6-2596.10" *)
  wire n186;
  (* src = "chal.v:334.5-334.8" *)
  reg n19 = 1'h0;
  (* src = "chal.v:349.5-349.8" *)
  reg n20 = 1'h0;
  (* src = "chal.v:2644.6-2644.10" *)
  wire n202;
  (* src = "chal.v:2659.6-2659.10" *)
  wire n207;
  (* src = "chal.v:2662.6-2662.10" *)
  wire n208;
  (* src = "chal.v:2665.6-2665.10" *)
  wire n209;
  (* src = "chal.v:2674.6-2674.10" *)
  wire n212;
  (* src = "chal.v:2680.6-2680.10" *)
  wire n214;
  (* src = "chal.v:2686.6-2686.10" *)
  wire n216;
  (* src = "chal.v:2689.6-2689.10" *)
  wire n217;
  (* src = "chal.v:2692.6-2692.10" *)
  wire n218;
  (* src = "chal.v:2695.6-2695.10" *)
  wire n219;
  (* src = "chal.v:376.5-376.8" *)
  reg n22 = 1'h0;
  (* src = "chal.v:2698.6-2698.10" *)
  wire n220;
  (* src = "chal.v:2701.6-2701.10" *)
  wire n221;
  (* src = "chal.v:2713.6-2713.10" *)
  wire n225;
  (* src = "chal.v:2716.6-2716.10" *)
  wire n226;
  (* src = "chal.v:2719.6-2719.10" *)
  wire n227;
  (* src = "chal.v:2722.6-2722.10" *)
  wire n228;
  (* src = "chal.v:2725.6-2725.10" *)
  wire n229;
  (* src = "chal.v:390.5-390.8" *)
  reg n23 = 1'h0;
  (* src = "chal.v:2728.6-2728.10" *)
  wire n230;
  (* src = "chal.v:2737.6-2737.10" *)
  wire n233;
  (* src = "chal.v:2743.6-2743.10" *)
  wire n235;
  (* src = "chal.v:2746.6-2746.10" *)
  wire n236;
  (* src = "chal.v:2752.6-2752.10" *)
  wire n238;
  (* src = "chal.v:2755.6-2755.10" *)
  wire n239;
  (* src = "chal.v:404.5-404.8" *)
  reg n24 = 1'h0;
  (* src = "chal.v:2761.6-2761.10" *)
  wire n241;
  (* src = "chal.v:2764.6-2764.10" *)
  wire n242;
  (* src = "chal.v:2767.6-2767.10" *)
  wire n243;
  (* src = "chal.v:2770.6-2770.10" *)
  wire n244;
  (* src = "chal.v:2773.6-2773.10" *)
  wire n245;
  (* src = "chal.v:2779.6-2779.10" *)
  wire n247;
  (* src = "chal.v:2785.6-2785.10" *)
  wire n249;
  (* src = "chal.v:418.6-418.9" *)
  wire n25;
  (* src = "chal.v:2788.6-2788.10" *)
  wire n250;
  (* src = "chal.v:2791.6-2791.10" *)
  wire n251;
  (* src = "chal.v:2794.6-2794.10" *)
  wire n252;
  (* src = "chal.v:2797.6-2797.10" *)
  wire n253;
  (* src = "chal.v:2806.6-2806.10" *)
  wire n255;
  (* src = "chal.v:2809.6-2809.10" *)
  wire n256;
  (* src = "chal.v:2812.6-2812.10" *)
  wire n257;
  (* src = "chal.v:2815.6-2815.10" *)
  wire n258;
  (* src = "chal.v:2818.6-2818.10" *)
  wire n259;
  (* src = "chal.v:445.5-445.8" *)
  reg n26 = 1'h0;
  (* src = "chal.v:2824.6-2824.10" *)
  wire n261;
  (* src = "chal.v:2827.6-2827.10" *)
  wire n262;
  (* src = "chal.v:2830.6-2830.10" *)
  wire n263;
  (* src = "chal.v:2833.6-2833.10" *)
  wire n264;
  (* src = "chal.v:2836.6-2836.10" *)
  wire n265;
  (* src = "chal.v:2839.6-2839.10" *)
  wire n266;
  (* src = "chal.v:2842.6-2842.10" *)
  wire n267;
  (* src = "chal.v:2848.6-2848.10" *)
  wire n269;
  (* src = "chal.v:459.5-459.8" *)
  reg n27 = 1'h0;
  (* src = "chal.v:2851.6-2851.10" *)
  wire n270;
  (* src = "chal.v:2854.6-2854.10" *)
  wire n271;
  (* src = "chal.v:2857.6-2857.10" *)
  wire n272;
  (* src = "chal.v:2860.6-2860.10" *)
  wire n273;
  (* src = "chal.v:2863.6-2863.10" *)
  wire n274;
  (* src = "chal.v:2866.6-2866.10" *)
  wire n275;
  (* src = "chal.v:2869.6-2869.10" *)
  wire n276;
  (* src = "chal.v:2872.6-2872.10" *)
  wire n277;
  (* src = "chal.v:2875.6-2875.10" *)
  wire n278;
  (* src = "chal.v:2878.6-2878.10" *)
  wire n279;
  (* src = "chal.v:473.5-473.8" *)
  reg n28 = 1'h0;
  (* src = "chal.v:2881.6-2881.10" *)
  wire n280;
  (* src = "chal.v:2884.6-2884.10" *)
  wire n281;
  (* src = "chal.v:2890.6-2890.10" *)
  wire n283;
  (* src = "chal.v:2893.6-2893.10" *)
  wire n284;
  (* src = "chal.v:2896.6-2896.10" *)
  wire n285;
  (* src = "chal.v:2899.6-2899.10" *)
  wire n286;
  (* src = "chal.v:2902.6-2902.10" *)
  wire n287;
  (* src = "chal.v:2905.6-2905.10" *)
  wire n288;
  (* src = "chal.v:2908.6-2908.10" *)
  wire n289;
  (* src = "chal.v:487.5-487.8" *)
  reg n29 = 1'h0;
  (* src = "chal.v:2911.6-2911.10" *)
  wire n290;
  (* src = "chal.v:2914.6-2914.10" *)
  wire n291;
  (* src = "chal.v:2917.6-2917.10" *)
  wire n292;
  (* src = "chal.v:2920.6-2920.10" *)
  wire n293;
  (* src = "chal.v:2923.6-2923.10" *)
  wire n294;
  (* src = "chal.v:2926.6-2926.10" *)
  wire n295;
  (* src = "chal.v:2929.6-2929.10" *)
  wire n296;
  (* src = "chal.v:2932.6-2932.10" *)
  wire n297;
  (* src = "chal.v:2935.6-2935.10" *)
  wire n298;
  (* src = "chal.v:70.6-70.8" *)
  wire n3;
  (* src = "chal.v:502.5-502.8" *)
  reg n30 = 1'h0;
  (* src = "chal.v:2944.6-2944.10" *)
  wire n301;
  (* src = "chal.v:2950.6-2950.10" *)
  wire n303;
  (* src = "chal.v:2953.6-2953.10" *)
  wire n304;
  (* src = "chal.v:2956.6-2956.10" *)
  wire n305;
  (* src = "chal.v:2962.6-2962.10" *)
  wire n307;
  (* src = "chal.v:2965.6-2965.10" *)
  wire n308;
  (* src = "chal.v:516.5-516.8" *)
  reg n31 = 1'h0;
  (* src = "chal.v:2971.6-2971.10" *)
  wire n310;
  (* src = "chal.v:2974.6-2974.10" *)
  wire n311;
  (* src = "chal.v:2977.6-2977.10" *)
  wire n312;
  (* src = "chal.v:2983.6-2983.10" *)
  wire n314;
  (* src = "chal.v:2986.6-2986.10" *)
  wire n315;
  (* src = "chal.v:2989.6-2989.10" *)
  wire n316;
  (* src = "chal.v:2992.6-2992.10" *)
  wire n317;
  (* src = "chal.v:2995.6-2995.10" *)
  wire n318;
  (* src = "chal.v:2998.6-2998.10" *)
  wire n319;
  (* src = "chal.v:3007.6-3007.10" *)
  wire n322;
  (* src = "chal.v:3010.6-3010.10" *)
  wire n323;
  (* src = "chal.v:3013.6-3013.10" *)
  wire n324;
  (* src = "chal.v:3016.6-3016.10" *)
  wire n325;
  (* src = "chal.v:3019.6-3019.10" *)
  wire n326;
  (* src = "chal.v:3022.6-3022.10" *)
  wire n327;
  (* src = "chal.v:3025.6-3025.10" *)
  wire n328;
  (* src = "chal.v:3028.6-3028.10" *)
  wire n329;
  (* src = "chal.v:3031.6-3031.10" *)
  wire n330;
  (* src = "chal.v:3037.6-3037.10" *)
  wire n332;
  (* src = "chal.v:3040.6-3040.10" *)
  wire n333;
  (* src = "chal.v:3043.6-3043.10" *)
  wire n334;
  (* src = "chal.v:3046.6-3046.10" *)
  wire n335;
  (* src = "chal.v:3052.6-3052.10" *)
  wire n336;
  (* src = "chal.v:3055.6-3055.10" *)
  wire n337;
  (* src = "chal.v:3061.6-3061.10" *)
  wire n339;
  (* src = "chal.v:556.6-556.9" *)
  wire n34;
  (* src = "chal.v:3064.6-3064.10" *)
  wire n340;
  (* src = "chal.v:3067.6-3067.10" *)
  wire n341;
  (* src = "chal.v:3073.6-3073.10" *)
  wire n343;
  (* src = "chal.v:3076.6-3076.10" *)
  wire n344;
  (* src = "chal.v:3079.6-3079.10" *)
  wire n345;
  (* src = "chal.v:3082.6-3082.10" *)
  wire n346;
  (* src = "chal.v:3088.6-3088.10" *)
  wire n348;
  (* src = "chal.v:3091.6-3091.10" *)
  wire n349;
  (* src = "chal.v:3094.6-3094.10" *)
  wire n350;
  (* src = "chal.v:3097.6-3097.10" *)
  wire n351;
  (* src = "chal.v:3100.6-3100.10" *)
  wire n352;
  (* src = "chal.v:3103.6-3103.10" *)
  wire n353;
  (* src = "chal.v:3106.6-3106.10" *)
  wire n354;
  (* src = "chal.v:592.5-592.8" *)
  reg n36 = 1'h0;
  (* src = "chal.v:607.5-607.8" *)
  reg n37 = 1'h0;
  (* src = "chal.v:661.5-661.8" *)
  reg n41 = 1'h0;
  (* src = "chal.v:676.5-676.8" *)
  reg n42 = 1'h0;
  (* src = "chal.v:703.5-703.8" *)
  reg n44 = 1'h0;
  (* src = "chal.v:718.5-718.8" *)
  reg n45 = 1'h0;
  (* src = "chal.v:733.5-733.8" *)
  reg n46 = 1'h0;
  (* src = "chal.v:747.5-747.8" *)
  reg n47 = 1'h0;
  (* src = "chal.v:761.5-761.8" *)
  reg n48 = 1'h0;
  (* src = "chal.v:133.5-133.7" *)
  reg n5 = 1'h0;
  (* src = "chal.v:789.5-789.8" *)
  reg n50 = 1'h0;
  (* src = "chal.v:803.5-803.8" *)
  reg n51 = 1'h0;
  (* src = "chal.v:818.5-818.8" *)
  reg n52 = 1'h0;
  (* src = "chal.v:831.5-831.8" *)
  reg n53 = 1'h0;
  (* src = "chal.v:859.5-859.8" *)
  reg n55 = 1'h0;
  (* src = "chal.v:873.5-873.8" *)
  reg n56 = 1'h0;
  (* src = "chal.v:908.5-908.8" *)
  reg n58 = 1'h0;
  (* src = "chal.v:148.5-148.7" *)
  reg n6 = 1'h0;
  (* src = "chal.v:1009.5-1009.8" *)
  reg n60 = 1'h0;
  (* src = "chal.v:1029.5-1029.8" *)
  reg n61 = 1'h0;
  (* src = "chal.v:1099.5-1099.8" *)
  reg n64 = 1'h0;
  (* src = "chal.v:1193.6-1193.9" *)
  wire n67;
  (* src = "chal.v:1206.6-1206.9" *)
  wire n68;
  (* src = "chal.v:1219.6-1219.9" *)
  wire n69;
  (* src = "chal.v:162.5-162.7" *)
  reg n7 = 1'h0;
  (* src = "chal.v:1232.6-1232.9" *)
  wire n70;
  (* src = "chal.v:1245.6-1245.9" *)
  wire n71;
  (* src = "chal.v:1258.6-1258.9" *)
  wire n72;
  (* src = "chal.v:1271.6-1271.9" *)
  wire n73;
  (* src = "chal.v:1284.5-1284.8" *)
  reg n74 = 1'h0;
  (* src = "chal.v:1303.6-1303.9" *)
  wire n75;
  (* src = "chal.v:1316.6-1316.9" *)
  wire n76;
  (* src = "chal.v:1350.6-1350.9" *)
  wire n77;
  (* src = "chal.v:1363.6-1363.9" *)
  wire n78;
  (* src = "chal.v:1376.6-1376.9" *)
  wire n79;
  (* src = "chal.v:177.5-177.7" *)
  reg n8 = 1'h0;
  (* src = "chal.v:1389.6-1389.9" *)
  wire n80;
  (* src = "chal.v:1402.6-1402.9" *)
  wire n81;
  (* src = "chal.v:1415.6-1415.9" *)
  wire n82;
  (* src = "chal.v:1428.5-1428.8" *)
  reg n83 = 1'h0;
  (* src = "chal.v:1452.6-1452.9" *)
  wire n84;
  (* src = "chal.v:1465.6-1465.9" *)
  wire n85;
  (* src = "chal.v:1478.6-1478.9" *)
  wire n86;
  (* src = "chal.v:1491.6-1491.9" *)
  wire n87;
  (* src = "chal.v:1504.6-1504.9" *)
  wire n88;
  (* src = "chal.v:1517.6-1517.9" *)
  wire n89;
  (* src = "chal.v:197.5-197.7" *)
  reg n9 = 1'h0;
  (* src = "chal.v:1530.6-1530.9" *)
  wire n90;
  (* src = "chal.v:1543.6-1543.9" *)
  wire n91;
  (* src = "chal.v:1556.6-1556.9" *)
  wire n92;
  (* src = "chal.v:1569.6-1569.9" *)
  wire n93;
  (* src = "chal.v:1582.6-1582.9" *)
  wire n94;
  (* src = "chal.v:1595.6-1595.9" *)
  wire n95;
  (* src = "chal.v:1608.6-1608.9" *)
  wire n96;
  (* src = "chal.v:1621.6-1621.9" *)
  wire n97;
  (* src = "chal.v:1634.6-1634.9" *)
  wire n98;
  (* src = "chal.v:1647.6-1647.9" *)
  wire n99;
  assign n243 = ~n116;
  assign n219 = ~n115;
  assign n307 = ~n114;
  assign n297 = ~n112;
  assign n285 = ~n111;
  assign n228 = ~n105;
  assign n214 = ~n104;
  assign _031_ = n83 | n138;
  assign _032_ = _031_ | n102;
  assign _033_ = _032_ | n103;
  assign _034_ = n214 & ~(_033_);
  assign _035_ = _034_ | n228;
  assign _036_ = n106 & ~(_035_);
  assign _037_ = _036_ | n107;
  assign _038_ = n285 & ~(_037_);
  assign _039_ = n119 & ~(_038_);
  assign _040_ = n297 & ~(_039_);
  assign _041_ = n113 & ~(_040_);
  assign _042_ = n307 & ~(_041_);
  assign _043_ = _042_ | n219;
  assign _044_ = _043_ | n243;
  assign _045_ = n117 & ~(_044_);
  assign _046_ = _045_ | n120;
  assign _047_ = _046_ | n121;
  assign _048_ = _047_ | n122;
  assign _049_ = _048_ | n123;
  assign _050_ = _049_ | n124;
  assign _051_ = _050_ | n125;
  assign _052_ = _051_ | n126;
  assign _053_ = _052_ | n127;
  assign _054_ = _053_ | n129;
  assign _055_ = _054_ | n130;
  assign _056_ = _055_ | n131;
  assign _057_ = _056_ | n132;
  assign _058_ = _057_ | n133;
  assign _059_ = _058_ | n134;
  assign _060_ = _059_ | n135;
  assign _061_ = _060_ | n136;
  assign _062_ = _061_ | n64;
  assign _063_ = ~(io_21_0_1 | io_19_0_1);
  assign _064_ = _063_ & ~(_062_);
  assign _065_ = n107 | n104;
  assign _066_ = _065_ | n111;
  assign _067_ = _066_ | n103;
  assign _068_ = n121 | n112;
  assign _069_ = _068_ | n120;
  assign _070_ = _069_ | n114;
  assign _071_ = n124 | n123;
  assign _072_ = _071_ | n122;
  assign _073_ = _072_ | n125;
  assign _074_ = n131 | n129;
  assign _075_ = _074_ | n133;
  assign _076_ = _075_ | n126;
  assign _077_ = _076_ | _073_;
  assign _078_ = _077_ | _070_;
  assign _079_ = _078_ | _067_;
  assign n110 = ~n119;
  assign _080_ = ~(n113 & n105);
  assign _081_ = _080_ | n110;
  assign _082_ = n106 & ~(_081_);
  assign _083_ = n135 | n102;
  assign _084_ = _083_ | n83;
  assign _085_ = _084_ | n136;
  assign n273 = ~n117;
  assign _086_ = n138 | ~(n115);
  assign _087_ = _086_ | n273;
  assign _088_ = _087_ | n243;
  assign _089_ = n127 | n130;
  assign _090_ = _089_ | n132;
  assign _091_ = _090_ | n134;
  assign _092_ = _091_ | _088_;
  assign _093_ = _092_ | _085_;
  assign _094_ = _082_ & ~(_093_);
  assign _095_ = _064_ & ~(_094_);
  assign _096_ = _079_ ? _064_ : _095_;
  assign _097_ = ~n64;
  assign n329 = ~n127;
  assign n233 = ~n126;
  assign n318 = ~n125;
  assign n220 = ~n124;
  assign n271 = ~n123;
  assign n208 = ~n122;
  assign n261 = ~n121;
  assign n217 = ~n120;
  assign n279 = ~n113;
  assign n241 = ~n107;
  assign n227 = ~n106;
  assign n216 = ~n103;
  assign n266 = ~n102;
  assign _098_ = ~(n83 & n138);
  assign _099_ = _098_ | n266;
  assign _100_ = _099_ | n216;
  assign _101_ = _100_ | n214;
  assign _102_ = _101_ | n228;
  assign _103_ = _102_ | n227;
  assign _104_ = _103_ | n241;
  assign _105_ = _104_ | n285;
  assign _106_ = _105_ | n110;
  assign _107_ = _106_ | n297;
  assign _108_ = _107_ | n279;
  assign _109_ = _108_ | n307;
  assign _110_ = _109_ | n219;
  assign _111_ = _110_ | n243;
  assign _112_ = _111_ | n273;
  assign _113_ = _112_ | n217;
  assign _114_ = _113_ | n261;
  assign _115_ = _114_ | n208;
  assign _116_ = _115_ | n271;
  assign _117_ = _116_ | n220;
  assign _118_ = _117_ | n318;
  assign _119_ = _118_ | n233;
  assign _120_ = _119_ | n329;
  assign _121_ = _120_ & _096_;
  assign _016_ = _097_ & ~(_121_);
  assign _122_ = _101_ & _096_;
  assign _029_ = _097_ & ~(_122_);
  assign _123_ = _118_ & _096_;
  assign _022_ = _097_ & ~(_123_);
  assign _124_ = _114_ & _096_;
  assign _017_ = _097_ & ~(_124_);
  assign n244 = ~n132;
  assign n263 = ~n131;
  assign n230 = ~n130;
  assign n207 = ~n129;
  assign _125_ = _120_ | n207;
  assign _126_ = _125_ | n230;
  assign _127_ = _126_ | n263;
  assign _128_ = _127_ | n244;
  assign _129_ = _128_ & _096_;
  assign _028_ = _097_ & ~(_129_);
  assign _130_ = _100_ & _096_;
  assign _018_ = _097_ & ~(_130_);
  assign _131_ = _111_ & _096_;
  assign _027_ = _097_ & ~(_131_);
  assign _132_ = _109_ & _096_;
  assign _019_ = _097_ & ~(_132_);
  assign _133_ = _115_ & _096_;
  assign _026_ = _097_ & ~(_133_);
  assign _134_ = _099_ & _096_;
  assign _025_ = _097_ & ~(_134_);
  assign _135_ = _116_ & _096_;
  assign _020_ = _097_ & ~(_135_);
  assign _136_ = _126_ & _096_;
  assign _024_ = _097_ & ~(_136_);
  assign _137_ = _102_ & _096_;
  assign _021_ = _097_ & ~(_137_);
  assign _138_ = _113_ & _096_;
  assign _023_ = _097_ & ~(_138_);
  assign _139_ = _107_ & _096_;
  assign _015_ = _097_ & ~(_139_);
  assign _140_ = _098_ & _096_;
  assign _014_ = _097_ & ~(_140_);
  assign n286 = ~n135;
  assign n274 = ~n133;
  assign _141_ = _128_ | n274;
  assign _142_ = n134 & ~(_141_);
  assign _143_ = _142_ & ~(n286);
  assign _144_ = _096_ & ~(_143_);
  assign _013_ = _097_ & ~(_144_);
  assign _145_ = _112_ & _096_;
  assign _012_ = _097_ & ~(_145_);
  assign _146_ = _105_ & _096_;
  assign _011_ = _097_ & ~(_146_);
  assign _147_ = _119_ & _096_;
  assign _010_ = _097_ & ~(_147_);
  assign _148_ = _141_ & _096_;
  assign _009_ = _097_ & ~(_148_);
  assign _149_ = _103_ & _096_;
  assign _008_ = _097_ & ~(_149_);
  assign _150_ = _117_ & _096_;
  assign _007_ = _097_ & ~(_150_);
  assign _151_ = _127_ & _096_;
  assign _006_ = _097_ & ~(_151_);
  assign _152_ = _110_ & _096_;
  assign _005_ = _097_ & ~(_152_);
  assign _153_ = _096_ & ~(n138);
  assign _004_ = _097_ & ~(_153_);
  assign _154_ = _125_ & _096_;
  assign _003_ = _097_ & ~(_154_);
  assign _155_ = _108_ & _096_;
  assign _002_ = _097_ & ~(_155_);
  assign _156_ = _106_ & _096_;
  assign _001_ = _097_ & ~(_156_);
  assign _157_ = _096_ & ~(_142_);
  assign _000_ = _097_ & ~(_157_);
  assign _158_ = _104_ & _096_;
  assign _030_ = _097_ & ~(_158_);
  assign n247 = ~io_18_31_0;
  assign n258 = ~n134;
  assign n269 = ~n136;
  assign n186 = ~n138;
  assign n312 = ~n83;
  assign _159_ = _094_ | _062_;
  assign _160_ = _079_ ? _062_ : _159_;
  assign _161_ = _097_ & ~(_063_);
  assign n25 = _160_ & ~(_161_);
  assign n3 = n64 & ~(_063_);
  assign _201_ = ~n3;
  assign _162_ = n26 & n56;
  assign _163_ = n6 & n11;
  assign _164_ = _163_ & n12;
  assign _165_ = ~(_164_ & n7);
  assign _166_ = n8 & n60;
  assign _167_ = _166_ & n50;
  assign _168_ = ~(_167_ & n55);
  assign _169_ = n23 & n48;
  assign _170_ = _169_ & n20;
  assign _171_ = ~(_170_ & n24);
  assign _172_ = _171_ | _168_;
  assign _173_ = _172_ | _165_;
  assign _174_ = _162_ & ~(_173_);
  assign _175_ = n44 | n41;
  assign _176_ = _175_ | n37;
  assign _177_ = _176_ | n36;
  assign _178_ = n58 | n52;
  assign _179_ = _178_ | n61;
  assign _180_ = n46 | n47;
  assign _181_ = _180_ | n45;
  assign _182_ = _181_ | n42;
  assign _183_ = _182_ | _179_;
  assign _184_ = _183_ | _177_;
  assign _185_ = n29 | n28;
  assign _186_ = _185_ | n30;
  assign _187_ = _186_ | n31;
  assign _188_ = n74 | ~(n27);
  assign _189_ = ~(_188_ | n53);
  assign _190_ = ~(_189_ & n51);
  assign _191_ = n14 | n10;
  assign _192_ = _191_ | n9;
  assign _193_ = _192_ | n5;
  assign _194_ = n19 | n22;
  assign _195_ = _194_ | n16;
  assign _196_ = _195_ | n18;
  assign _197_ = _196_ | _193_;
  assign _198_ = _197_ | _190_;
  assign _199_ = _198_ | _187_;
  assign _200_ = _199_ | _184_;
  assign n236 = _174_ & ~(_200_);
  (* src = "chal.v:3317.19-3317.82" *)
  always @(posedge io_12_31_1)
    if (n3) n51 <= n27;
  (* src = "chal.v:3457.19-3457.81" *)
  always @(posedge io_12_31_1)
    if (_015_)
      if (!_096_) n113 <= 1'h0;
      else n113 <= n279;
  (* src = "chal.v:3456.19-3456.81" *)
  always @(posedge io_12_31_1)
    if (n3) n9 <= n12;
  (* src = "chal.v:3451.19-3451.81" *)
  always @(posedge io_12_31_1)
    if (_014_)
      if (!_096_) n102 <= 1'h0;
      else n102 <= n266;
  (* src = "chal.v:3450.19-3450.82" *)
  always @(posedge io_12_31_1)
    if (n3)
      if (io_21_0_1) n60 <= 1'h0;
      else n60 <= io_19_0_1;
  (* src = "chal.v:3452.19-3452.82" *)
  always @(posedge io_12_31_1)
    if (n3) n56 <= n61;
  (* src = "chal.v:3449.19-3449.81" *)
  always @(posedge io_12_31_1)
    if (n3) n6 <= n7;
  (* src = "chal.v:3447.19-3447.81" *)
  always @(posedge io_12_31_1)
    if (_013_)
      if (!_096_) n136 <= 1'h0;
      else n136 <= n269;
  (* src = "chal.v:3448.19-3448.82" *)
  always @(posedge io_12_31_1)
    if (n3) n37 <= n51;
  (* src = "chal.v:3444.19-3444.81" *)
  always @(posedge io_12_31_1)
    if (_012_)
      if (!_096_) n120 <= 1'h0;
      else n120 <= n217;
  (* src = "chal.v:3443.19-3443.81" *)
  always @(posedge io_12_31_1)
    if (_011_)
      if (!_096_) n119 <= 1'h0;
      else n119 <= n110;
  (* src = "chal.v:3446.19-3446.82" *)
  always @(posedge io_12_31_1)
    if (n3) n16 <= n11;
  (* src = "chal.v:3439.19-3439.82" *)
  always @(posedge io_12_31_1)
    if (n3) n23 <= n24;
  (* src = "chal.v:3437.19-3437.81" *)
  always @(posedge io_12_31_1)
    if (n3) n5 <= n29;
  (* src = "chal.v:3434.19-3434.81" *)
  always @(posedge io_12_31_1)
    if (_010_)
      if (!_096_) n127 <= 1'h0;
      else n127 <= n329;
  (* src = "chal.v:3433.19-3433.81" *)
  always @(posedge io_12_31_1)
    if (_009_)
      if (!_096_) n134 <= 1'h0;
      else n134 <= n258;
  (* src = "chal.v:3435.19-3435.82" *)
  always @(posedge io_12_31_1)
    if (n3) n28 <= n26;
  (* src = "chal.v:3432.19-3432.82" *)
  always @(posedge io_12_31_1)
    if (n3) n14 <= n10;
  (* src = "chal.v:3430.19-3430.82" *)
  always @(posedge io_12_31_1)
    if (n3) n61 <= n45;
  (* src = "chal.v:3428.19-3428.81" *)
  always @(posedge io_12_31_1)
    if (_008_)
      if (!_096_) n107 <= 1'h0;
      else n107 <= n241;
  (* src = "chal.v:3429.19-3429.82" *)
  always @(posedge io_12_31_1)
    if (n3) n41 <= n19;
  (* src = "chal.v:3423.19-3423.81" *)
  always @(posedge io_12_31_1)
    if (_007_)
      if (!_096_) n125 <= 1'h0;
      else n125 <= n318;
  (* src = "chal.v:3422.19-3422.81" *)
  always @(posedge io_12_31_1)
    if (_006_)
      if (!_096_) n132 <= 1'h0;
      else n132 <= n244;
  (* src = "chal.v:3421.19-3421.81" *)
  always @(posedge io_12_31_1)
    if (_005_)
      if (!_096_) n116 <= 1'h0;
      else n116 <= n243;
  (* src = "chal.v:3424.19-3424.82" *)
  always @(posedge io_12_31_1)
    if (n3) n26 <= n30;
  (* src = "chal.v:3417.19-3417.80" *)
  always @(posedge io_12_31_1)
    if (_004_)
      if (!_096_) n83 <= 1'h0;
      else n83 <= n312;
  (* src = "chal.v:3420.19-3420.82" *)
  always @(posedge io_12_31_1)
    if (n3) n48 <= n44;
  (* src = "chal.v:3413.19-3413.81" *)
  always @(posedge io_12_31_1)
    if (_003_)
      if (!_096_) n130 <= 1'h0;
      else n130 <= n230;
  (* src = "chal.v:3412.19-3412.81" *)
  always @(posedge io_12_31_1)
    if (_002_)
      if (!_096_) n114 <= 1'h0;
      else n114 <= n307;
  (* src = "chal.v:3415.19-3415.82" *)
  always @(posedge io_12_31_1)
    if (n3) n19 <= n23;
  (* src = "chal.v:3410.19-3410.82" *)
  always @(posedge io_12_31_1)
    if (n3) n46 <= n37;
  (* src = "chal.v:3402.19-3402.81" *)
  always @(posedge io_12_31_1)
    if (_001_)
      if (!_096_) n112 <= 1'h0;
      else n112 <= n297;
  (* src = "chal.v:3403.19-3403.82" *)
  always @(posedge io_12_31_1)
    if (n3) n31 <= n53;
  (* src = "chal.v:3401.19-3401.83" *)
  always @(posedge io_12_31_1)
    if (n236) n58 <= 1'h1;
  (* src = "chal.v:3400.19-3400.82" *)
  always @(posedge io_12_31_1)
    if (n3) n44 <= n41;
  (* src = "chal.v:3396.19-3396.82" *)
  always @(posedge io_12_31_1)
    if (n3) n24 <= n18;
  (* src = "chal.v:3395.19-3395.81" *)
  always @(posedge io_12_31_1)
    if (n25) n64 <= _201_;
  (* src = "chal.v:3393.19-3393.82" *)
  always @(posedge io_12_31_1)
    if (n3) n36 <= n48;
  (* src = "chal.v:3391.19-3391.81" *)
  always @(posedge io_12_31_1)
    if (_000_)
      if (!_096_) n135 <= 1'h0;
      else n135 <= n286;
  (* src = "chal.v:3390.19-3390.81" *)
  always @(posedge io_12_31_1)
    if (_030_)
      if (!_096_) n111 <= 1'h0;
      else n111 <= n285;
  (* src = "chal.v:3392.19-3392.82" *)
  always @(posedge io_12_31_1)
    if (n3) n29 <= n28;
  (* src = "chal.v:3389.19-3389.82" *)
  always @(posedge io_12_31_1)
    if (n3) n12 <= n14;
  (* src = "chal.v:3388.19-3388.82" *)
  always @(posedge io_12_31_1)
    if (n3) n42 <= n46;
  (* src = "chal.v:3381.19-3381.81" *)
  always @(posedge io_12_31_1)
    if (_029_)
      if (!_096_) n105 <= 1'h0;
      else n105 <= n228;
  (* src = "chal.v:3382.19-3382.82" *)
  always @(posedge io_12_31_1)
    if (n3) n22 <= n16;
  (* src = "chal.v:3379.19-3379.81" *)
  always @(posedge io_12_31_1)
    if (_028_)
      if (!_096_) n133 <= 1'h0;
      else n133 <= n274;
  (* src = "chal.v:3378.19-3378.81" *)
  always @(posedge io_12_31_1)
    if (_027_)
      if (!_096_) n117 <= 1'h0;
      else n117 <= n273;
  (* src = "chal.v:3380.19-3380.82" *)
  always @(posedge io_12_31_1)
    if (n3) n27 <= n36;
  (* src = "chal.v:3376.19-3376.81" *)
  always @(posedge io_12_31_1)
    if (_026_)
      if (!_096_) n123 <= 1'h0;
      else n123 <= n271;
  (* src = "chal.v:3377.19-3377.82" *)
  always @(posedge io_12_31_1)
    if (n3) n52 <= n55;
  (* src = "chal.v:3370.19-3370.81" *)
  always @(posedge io_12_31_1)
    if (_025_)
      if (!_096_) n103 <= 1'h0;
      else n103 <= n216;
  (* src = "chal.v:3375.19-3375.82" *)
  always @(posedge io_12_31_1)
    if (n3) n10 <= n6;
  (* src = "chal.v:3368.19-3368.81" *)
  always @(posedge io_12_31_1)
    if (_024_)
      if (!_096_) n131 <= 1'h0;
      else n131 <= n263;
  (* src = "chal.v:3369.19-3369.81" *)
  always @(posedge io_12_31_1)
    if (n3) n7 <= n8;
  (* src = "chal.v:3366.19-3366.81" *)
  always @(posedge io_12_31_1)
    if (_023_)
      if (!_096_) n121 <= 1'h0;
      else n121 <= n261;
  (* src = "chal.v:3367.19-3367.82" *)
  always @(posedge io_12_31_1)
    if (n3) n50 <= n56;
  (* src = "chal.v:3360.19-3360.81" *)
  always @(posedge io_12_31_1)
    if (!n64)
      if (!_096_) n138 <= 1'h0;
      else n138 <= n186;
  (* src = "chal.v:3364.19-3364.82" *)
  always @(posedge io_12_31_1)
    if (n3) n47 <= n42;
  (* src = "chal.v:3355.19-3355.90" *)
  always @(posedge io_12_31_1)
    if (n236) io_18_31_0 <= n247;
  (* src = "chal.v:3353.19-3353.82" *)
  always @(posedge io_12_31_1)
    if (n3) n45 <= n47;
  (* src = "chal.v:3347.19-3347.82" *)
  always @(posedge io_12_31_1)
    if (n3) n74 <= n60;
  (* src = "chal.v:3346.19-3346.82" *)
  always @(posedge io_12_31_1)
    if (n3) n30 <= n31;
  (* src = "chal.v:3341.19-3341.81" *)
  always @(posedge io_12_31_1)
    if (_022_)
      if (!_096_) n126 <= 1'h0;
      else n126 <= n233;
  (* src = "chal.v:3335.19-3335.81" *)
  always @(posedge io_12_31_1)
    if (_021_)
      if (!_096_) n106 <= 1'h0;
      else n106 <= n227;
  (* src = "chal.v:3343.19-3343.82" *)
  always @(posedge io_12_31_1)
    if (n3) n55 <= n50;
  (* src = "chal.v:3334.19-3334.82" *)
  always @(posedge io_12_31_1)
    if (n3) n20 <= n22;
  (* src = "chal.v:3333.19-3333.81" *)
  always @(posedge io_12_31_1)
    if (n3) n8 <= n5;
  (* src = "chal.v:3328.19-3328.81" *)
  always @(posedge io_12_31_1)
    if (_020_)
      if (!_096_) n124 <= 1'h0;
      else n124 <= n220;
  (* src = "chal.v:3327.19-3327.81" *)
  always @(posedge io_12_31_1)
    if (_019_)
      if (!_096_) n115 <= 1'h0;
      else n115 <= n219;
  (* src = "chal.v:3329.19-3329.82" *)
  always @(posedge io_12_31_1)
    if (n3) n53 <= n74;
  (* src = "chal.v:3322.19-3322.81" *)
  always @(posedge io_12_31_1)
    if (_018_)
      if (!_096_) n104 <= 1'h0;
      else n104 <= n214;
  (* src = "chal.v:3326.19-3326.82" *)
  always @(posedge io_12_31_1)
    if (n3) n11 <= n9;
  (* src = "chal.v:3320.19-3320.82" *)
  always @(posedge io_12_31_1)
    if (n3) n18 <= n20;
  (* src = "chal.v:3316.19-3316.81" *)
  always @(posedge io_12_31_1)
    if (_017_)
      if (!_096_) n122 <= 1'h0;
      else n122 <= n208;
  (* src = "chal.v:3315.19-3315.81" *)
  always @(posedge io_12_31_1)
    if (_016_)
      if (!_096_) n129 <= 1'h0;
      else n129 <= n207;
  assign n101 = n186;
  assign n202 = n138;
  assign n209 = n27;
  assign n212 = n20;
  assign n218 = n9;
  assign n221 = n74;
  assign n225 = n5;
  assign n226 = n22;
  assign n229 = n208;
  assign n235 = n50;
  assign n238 = n31;
  assign n239 = n60;
  assign n242 = n220;
  assign n245 = n47;
  assign n249 = 1'h0;
  assign n250 = 1'h0;
  assign n251 = 1'h0;
  assign n252 = 1'h0;
  assign n253 = 1'h1;
  assign n255 = n186;
  assign n256 = n110;
  assign n257 = n233;
  assign n259 = n42;
  assign n262 = n56;
  assign n264 = n8;
  assign n265 = n216;
  assign n267 = 1'h1;
  assign n270 = n6;
  assign n272 = n55;
  assign n275 = n36;
  assign n276 = n228;
  assign n277 = n16;
  assign n278 = n214;
  assign n280 = n261;
  assign n281 = n207;
  assign n283 = n46;
  assign n284 = n14;
  assign n287 = n28;
  assign n288 = n48;
  assign n289 = n186;
  assign n290 = 1'h1;
  assign n291 = n18;
  assign n292 = n227;
  assign n293 = n219;
  assign n294 = n263;
  assign n295 = n41;
  assign n296 = 1'h1;
  assign n298 = n53;
  assign n301 = n25;
  assign n303 = n273;
  assign n304 = n274;
  assign n305 = n37;
  assign n308 = n230;
  assign n310 = n23;
  assign n311 = n285;
  assign n314 = n3;
  assign n315 = n44;
  assign n316 = n243;
  assign n317 = n244;
  assign n319 = n30;
  assign n322 = n297;
  assign n323 = n241;
  assign n324 = n19;
  assign n325 = n45;
  assign n326 = n271;
  assign n327 = n10;
  assign n328 = n258;
  assign n330 = n26;
  assign n332 = n29;
  assign n333 = 1'h0;
  assign n334 = 1'h0;
  assign n335 = 1'h1;
  assign n336 = n24;
  assign n337 = n307;
  assign n339 = n318;
  assign n34 = n236;
  assign n340 = n110;
  assign n341 = n217;
  assign n343 = n11;
  assign n344 = n269;
  assign n345 = n51;
  assign n346 = n7;
  assign n348 = n266;
  assign n349 = n61;
  assign n350 = n312;
  assign n351 = n329;
  assign n352 = n286;
  assign n353 = n12;
  assign n354 = n279;
  assign n67 = n312;
  assign n68 = n266;
  assign n69 = n216;
  assign n70 = n214;
  assign n71 = n228;
  assign n72 = n227;
  assign n73 = n241;
  assign n75 = n285;
  assign n76 = 1'h1;
  assign n77 = n297;
  assign n78 = n279;
  assign n79 = n307;
  assign n80 = n219;
  assign n81 = n243;
  assign n82 = n273;
  assign n84 = n217;
  assign n85 = n261;
  assign n86 = n208;
  assign n87 = n271;
  assign n88 = n220;
  assign n89 = n318;
  assign n90 = n233;
  assign n91 = n329;
  assign n92 = n207;
  assign n93 = n230;
  assign n94 = n263;
  assign n95 = n244;
  assign n96 = n274;
  assign n97 = n258;
  assign n98 = n286;
  assign n99 = n269;
endmodule
